### ISSUE TITLE
Custom single cell architectures

### ISSUE THREAD

**Issue by dawe** [haowenz/chromap#10]
As far as I understand, `chromap` is able to parse CB from a whitelist and look for it into a specific fastq file (`-b`). I wonder if it would be the time to create a flexible interface for CB and (possibly) UMIs. For example: in 10x data R2 contains CB and it is as long as required by CB; in SNARE-seq CB is in R1 but the read is longer, including the sections for UMI and a T-tail. Other technologies may introduce CB in the same read with genomic information. 
Other tools for scRNA-seq have tackled this before, I'm thinking to `bustools`, which allows custom architectures.

**Comment by haowenz** [comment]
Thanks for the suggestion. We would consider adding this feature in the future.

**Comment by haowenz** [comment]
@mourisl has added the support for this in a recent pull request which is merged in the master branch. You are welcomed to test it.

**Comment by dawe** [comment]
I definitely will, thank you. 
I’ll close this issue.
