### ISSUE TITLE
Expose running options

### ISSUE THREAD

**Issue by dawe** [haowenz/chromap#11]
When running `chromap` a lot of information is presented, detailing the options used for the run. I understand that some values can be selected using the `--preset` option but the user is limited to the chip/atac/hic choices. 
Will you expose all options to the user in the future?

**Comment by haowenz** [comment]
Actually you can tune most of the parameters you saw. If you run Chromap with -h, you would see the available options. I also want to mention that the preset parameters should be good enough to use in most cases.

**Comment by dawe** [comment]
Whoops, I apologize for not having RTFM this time.
