### ISSUE TITLE
Error fragments generated by chromap

### ISSUE THREAD

**Issue by Ruthwang123** [haowenz/chromap#112]
**My problem**
    When I use `MAESTRO` to process my scATAC data, I find the mapping result in bed format generated from `chromap` tends to have something wrong. (I have changed the chromap in MAESTRO to `Vision 0.2.2 `before). 
The length of chr4 is `190214555`, and I find that there are seven fragments  whose end positions  exceed the length of chr4.
```
chr4    190178101       190243580       TAGACGGATCGAGCGTTAGACGGA  1 
chr4    190179698       190245197       TAGTGACTTGAAGCCAGATAGAGG  2 
chr4    190179721       190245207       TCAGGAGGTCGTTAGCGACCTTAG  1 
chr4    190179687       190245212       GAGGTGCTTGCGTGAAGTGTGTCG  1 
chr4    190179723       190245224       GATTCATCACAGTGGTTAGAACAC  1 
chr4    190179744       190245234       TACAGGATTGTTCTCCTTCAGCTC  2 
chr4    190179833       190245309       TGATACGTTTGACTCTTCCAGTCG  1
```
I find out the sequences of these seven fragments in FASTQ files and  run chromap to process them again.  The output fragments are still the same as the above with the exceeded wrong ends.
*****************
**My code is here :**
The reference genome comes from
`http://cistrome.org/~galib/MAESTRO/references/scATAC/Refdata_scATAC_MAESTRO_GRCh38_1.1.0.tar.gz`
which is provided by MAESTRO tutorial.

```
#build  index for chromap
chromap -i -r Refdata_scATAC_MAESTRO_GRCh38_1.1.0/GRCh38_genome.fa -o GRCh38_chromap.index
```
```
#run chromap
chromap --preset atac -x /home/projects/ATAC/reference_genomic/scATAC/GRCh38_chromap.index \
-r  /home/projects/ATAC/reference_genomic/scATAC/Refdata_scATAC_MAESTRO_GRCh38_1.1.0/GRCh38_genome.fa  \
-1 /home/projects/ATAC/J061_ATAC_S1_L001_R1_004.fastq -2 /home/projects/ATAC/J061_ATAC_S1_L001_R3_004.fastq \
- o  fragments.bed  -b /home/projects/ATAC/J061_ATAC_S1_L001_R2_004.fastq \
-t 30 --barcode-whitelist /home/projects/ATAC/index_whitelist.txt
```
********************
Besides,  When I set the output  `-o` as  `--SAM`  in chromap to create the SAM file first, after sorting it by `samtools sort -n`  as well as using `bedtools bamtobed -bedpe ` option to generate the BEDPE file , it seems that there is nothing wrong with the result:
```
chr4    190179553       190179703       chr4    190179740       190179795       A00920:1011:HJF2HDSX3:2:1649:17282:4178 32      -       +
chr4    190179531       190179681       chr4    190179683       190179738       A00920:1011:HJF2HDSX3:2:2372:4598:20134 34      -       +
chr4    190179526       190179676       chr4    190179717       190179772       A00920:1011:HJF2HDSX3:2:2559:2248:33317 32      -       +
chr4    190179543       190179693       chr4    190179719       190179774       A01426:355:HHFLHDSX3:1:1358:7419:36385  37      -       +
chr4    190179628       190179778       chr4    190179829       190179884       A01426:355:HHFLHDSX3:1:2106:17906:31093 32      -       +
chr4    190177899       190178049       chr4    190178097       190178152       A01426:355:HHFLHDSX3:1:2357:26910:10958 38      -       +
chr4    190179516       190179666       chr4    190179694       190179749       A01426:355:HHFLHDSX3:1:2644:3956:17550  32      -       +
```
******************************
I am really confused about this problem. Actually, I'm a little worried about the alignment error which may influence other fragments that seem to be normal. In this fragment file, the number of the fragments is about 181M in total and seven fragments from chr4 go wrong. 

I provide the FASTQ file and barcode white list of the seven fragments for you to check the problem.
https://drive.google.com/drive/folders/1iqbiFE7GuBiUuF8GWFxNUdQIRrsnLXhc?usp=sharing

Thank you for your help!

**Comment by mourisl** [comment]
Thank you for letting us know about this issue and sharing the data. I just reproduced this issue and will work on fixing it.

**Comment by Ruthwang123** [comment]
Thank you for your reply and please let me know if you fix it. Have a nice day~
@mourisl

**Comment by mourisl** [comment]
@Ruthwang123 Sorry for the delayed reply. I think I've found the bug. Could you pull the "dev3" branch and "make clean; make" to remake Chromap and give it a try?

The bug is triggered when the two mates' read lengths differ too much, and some of the unqualified mappings might be falsely retained. This will cause a wrong estimation of fragment length in the bed output format.

**Comment by Ruthwang123** [comment]
@mourisl Thank you so much for your help and so sorry for the delayed reply.
I will try it and get back to you as soon as possible.
