### ISSUE TITLE
Output both pair and sam files for Hi-C

### ISSUE THREAD

**Issue by zhengrongbin** [haowenz/chromap#113]
Hi - thanks for developing Chromap which really works well and runs fast. I am analyzing Micro-C data, which has a higher resolution than Hi-C but also takes longer times to run by traditional aligners, so Chromap really helps in this. However, it seems that chromap cannot output pair file and sam file in the same run. I will need to run two times, by setting --pair or --SAM to get pair file and sam file separately. Please correct me if I am wrong. Is there a way to output both pair and sam files in one job? Thanks!

**Comment by mourisl** [comment]
I have also discussed this with Rongbin offline. So I think we can close this issue for now.
