### ISSUE TITLE
SAM output does not include mate-pair information with paired-end reads

### ISSUE THREAD

**Issue by bobbybobbobbo** [haowenz/chromap#124]
Thanks for developing this tool! The speed increases are very impressive and could help reduce our alignment times dramatically. However, I've run into the following issue when running chromap (v0.2.3-r407) on paired-end fastqs with the --SAM flag specified - the resulting SAM output does not report the position of the mate read or the observed template length. Here is an example of the output that chromap is producing:

```
A00873:709:HWT3VDSX3:2:2244:22200:23657	99	chr10	11385	20	150M	*	0	0	AGCGGGGAAGGAGCTTCGCGCTGCCGCTTGGCTGGGGACTGGACACCGCCCTCCCGCGGCTCCTGAGCCGGCTGCCACCAGGGGGCGCGCCAGCGGTGTCCGGGAGCCTAGCGGCGCGTGTGCAGCGGCCAGTGCACCTGCTCCGGCCCT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:2	MD:Z:42G100T6
A00873:709:HWT3VDSX3:2:2244:22200:23657	147	chr10	11596	20	150M	*	0	0	GCTCCAAGGNCTGAGACAGCACCCNCACCTGGCATTCAGCGCGCTCCCGGGGGCAGAGGTCGCGGTGTCCTCACGCTGTGGTGCCGGCCTACAACCCCCACGCCGGGCTCGGGCCCGGCGGAGGAGGGCGATGCTCCCCGGGTAGGACAA	:,,,F,FF:#F:F,FFF,:F,,FF#FF:F,:FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:5	MD:Z:6C2C3C7G2C125
A00873:709:HWT3VDSX3:2:2242:15239:1329	163	chr10	19691	0	150M	*	0	0	ATGAGCATTGGGTGAAAAACGAAATCAAGATGGAAATGTAAAAAATTTCTTCGAACTGGATGACACAACCTATCAAGACCTCTGGGATACAGCAAAGGCAGTGCGAAGAGGAAAGTTTGTAGCAANATACAACTACGTCTNAAAGTCTGA	:FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFF:,F:FFF:FFFFFFFF::FFFFF:FFFFFFFFFF:FFF:FFFFFFFFFFFFFFFFFFFF:,:FFFF:FFFF,FFFFFFFF,FFFF,:FF,:,#:FF,:,:FFF,FFF#,,:,,:,,F	NM:i:8	MD:Z:104t13a5ct1a3c7ga9
A00873:709:HWT3VDSX3:2:2242:15239:1329	83	chr10	19888	0	150M	*	0	0	GGAACAAGCCAAACCCAATCCCAGCAAACAAAGGAAATAACCAAGATCAGAGCAGAACTAAATGAAATTGACACAACAACAACAACAACAAAAATACAAAACATAAATAAAACAAAAATTTGGTTATTTGAAAAGATAAAATTGATAAAC	FFF,FFFFFFFFF:FF:,:F,FF::FFFF,F:FFFFF:F:FF:FFFFFF,FF,F:FF:FFF,FFF,,::FF:FF:FFFFFFFFFFFFFFFF,FFF,FFFFFF:F::FFFFFF:,FFF:FFF:F:F,FFFF:FFF:FF:FFF:FFFFFF:F	NM:i:0	MD:Z:150
```
The RNEXT, PNEXT and TLEN fields are all missing or reporting incorrect information. This makes it difficult to use SAM files produced by chromap for peak calling with MACS2 or other subsequent analysis. There appears to be no issue with detecting mate pairs with other output formats, but generating a SAM output would be most convenient for our purposes. Any insights or help with this would be greatly appreciated!

**Comment by swiftgenomics** [comment]
Please check the new release. These tags in SAM are now supported.

**Comment by bobbybobbobbo** [comment]
Thanks! I’ve closed the issue.

On 4 Jan 2023, at 16:50, swiftgenomics ***@***.******@***.***>> wrote:



Please check the new release. These tags in SAM are now supported.
