### ISSUE TITLE
MAPQ results in range 0-29

### ISSUE THREAD

**Issue by penneyc1** [haowenz/chromap#13]
Hi there, 

I recently started using chromap on some of my lab's CHIPseq reads and found that the outputted MAPQ scores (for 30-some input files) are all ranging from "0" to "29", with none higher than that. I'm wondering if you could think of a reason why this might be happening. Is there a setting I might have missed/something to do with a parameter that was set on the generation of our reference index file?

Thanks in advance for any help!

Best,
Chris

**Comment by mourisl** [comment]
Could you please show us the command when running Chromap? Is your data single-end?

**Comment by penneyc1** [comment]
Hi there, thanks for such a quick reply - yes, we're using single-end data. Here's the command I used:

./chromap --preset chip -x index_files/38.index -r ref_files/38ref.fna.gz -q 0 --output-mappings-not-in-whitelist -1 fastq/filename.fastq.gz -o outputfilename.bed

**Comment by mourisl** [comment]
We have found the issue regarding the low MAPQ for single-end data. Could you please git pull the updated version and give it a try? Thank you.

**Comment by penneyc1** [comment]
Hi there,

Seems to work for me now! Thank you guys.

Best,
Chris
