### ISSUE TITLE
[Feature Request] report number of duplicated fragments in bulk

### ISSUE THREAD

**Issue by dawe** [haowenz/chromap#145]
Hello and thanks once more for chromap.
I know for scATAC-seq data, the output BED file contains the duplicate_count in 5th column. I wonder if it would be possible to report this information also for bulk analysis, possibly using the 4th column (currently unassigned and set to `N`). I'm asking this as I would like to use such information for some QC. Having the duplicate count for each fragment could be used to derive some [ENCODE-like measures](https://www.encodeproject.org/data-standards/terms/#library), but also to streamline [decoratio analysis](https://www.biorxiv.org/content/10.1101/2022.10.10.511638v1). Currently I do both by running chromap without any duplicate removal and count them later.

**Comment by mourisl** [comment]
Thank you for the suggestion. Indeed, the duplication number should be included in the output for the bulk data as well. We will implement this in the next few days.

**Comment by mourisl** [comment]
We have added the duplicate number to the last column of the BED file for bulk analysis in the li_dev5 branch. Could you please check out that branch and give it a try to see whether it works on your data? Thank you.

**Comment by dawe** [comment]
It works, thank you! Can I start using this version or should I wait for the next official release?

**Comment by mourisl** [comment]
This branch will be the next official release if no other significant bug is found. I'm currently waiting for the #143 . Once it is resolved, we will draft a new release based on li_dev5.

I think you can use this version for now if it is time-sensitive.
