### ISSUE TITLE
[BUG] chromap map Hi-C short reads Parameters: error threshold

### ISSUE THREAD

**Issue by Hanjiangna** [haowenz/chromap#159]
I ran the chromap tool with Hi-C preset parameters on my data, and while the output SAM file (R0301onthap2.sam) was successfully generated, there was a message displayed that listed several mapping parameters:

Plaintext
Parameters: 
error threshold: 4,
min-num-seeds: 2,
max-seed-frequency: 500,1000, 
max-num-best-mappings: 1,
max-insert-size: 1000,
MAPQ-threshold: 1,
min-read-length: 30,
bc-error-threshold: 1,
bc-probability-threshold: 0.90
However, I am unsure if this constitutes an error or is just a status report of the used settings. Could you please clarify whether these parameter values indicate any issues in the processing? If it's indeed an error, what might be causing it, and how can I resolve it?
code
chromap  --preset hic -r R0301HifiHicOnt.asm.hic.hap2.p_ctg.fa  -x contigs.index --remove-pcr-duplicates -1 Rhc_1_clean.fastq.gz -2 Rhc_2_clean.fastq.gz --SAM -o R0301onthap2.sam -t 50

error
Parameters: error threshold: 4, min-num-seeds: 2, max-seed-frequency: 500,1000, max-num-best-mappings: 1, max-insert-size: 1000, MAPQ-threshold: 1, min-read-length: 30, bc-error-threshold: 1, bc-probability-threshold: 0.90
![image](https://github.com/haowenz/chromap/assets/116631936/f11f41c7-e41f-4e4e-b89b-edf40dc23b5f)

**Comment by mourisl** [comment]
This is not an error. They are for the log.

**Comment by Hanjiangna** [comment]
Thanks for the prompt response!
