### ISSUE TITLE
[BUG]For HiC data, the size of SAM files outputted using Chromap is much smaller compared to those from BWA-MEM

### ISSUE THREAD

**Issue by xujialupaoli** [haowenz/chromap#160]
Thank you for providing such a useful tool .
**Describe the bug**
I have a set of HiC data and I would like to split it by chromosome. I aligned the HiC data to a reference genome separately using BWA-MEM and Chromap, but the sizes of the SAM files they produced differ by a factor of 57.
My hic data is hu1_R1.fq.gz (82G), hu1_R2.fq.gz (86G). A total of 753,706,076 pairs of reads.
I installed BWA and Chromap using Conda.

**To Reproduce**
1）First, I aligned the HiC data to a reference genome using BWA-MEM.
bwa Version: 0.7.17-r1188
`bwa mem -5SPM -t 64 filtered.fa \
"hu1_R1.fq.gz" \
"hu1_R2.fq.gz" > aln_pe.sam `
2)Then,I aligned the HiC data to a reference genome  using chromap.
chromap Version:0.2.6-r490 
`chromap -i -r filtered.fa -o index`
`chromap --preset hic  -x index -r filtered.fa \
-1 "hu1_R1.fq.gz" \
-2 "hu1_R2.fq.gz" \
--SAM -o chromap.sam -t 64`
The screenshot of the log output by chromap：
![image](https://github.com/haowenz/chromap/assets/96410022/3e13866a-ee49-4de2-b290-aaaf8624a696)

**Expected behavior**
There are only 22131418 lines in the sam file output by chromap, which is far less than the number of reads.
![image](https://github.com/haowenz/chromap/assets/96410022/5546e941-88c2-4932-9ff7-58c547e730f5)
I expect the sizes of SAM files produced by two software to be similar. However, the SAM file size outputted by BWA mem is 861G, while the size from chromap is 15G. I don't understand why there's such a big difference. I'm unsure which SAM result to choose for splitting HiC reads mapped to different chromosomes.

[log_chromap.txt](https://github.com/haowenz/chromap/files/15051407/log_chromap.txt)

**Comment by mourisl** [comment]
Could you please check the mapq from the BWA output? Chromap by default will suppress alignments will mapq 0, so the number of alignments can be less than the input reads.

**Comment by mourisl** [comment]
You can use the option "-q 0" to output the mapq 0 reads. Chromap only outputs the primary alignments, so for hi-c, each split read will have one segment in the output. So I guess the SAM file will still be smaller than BWA-MEM's, but it won't be like this 10 times difference.

**Comment by xujialupaoli** [comment]
Thank you very much for your help.
