### ISSUE TITLE
Mapping paired-end single-cell ATAC-Seq reads

### ISSUE THREAD

**Issue by NPSDC** [haowenz/chromap#164]
I am trying to map paired-end reads. I wanted to understand how Chromap tackles a scenario when only one mate (single read) of the pair maps to the reference genome. Does it report the mapping for the pair or ignore it? If yes then is the fragment length the read length?

Thank you,
Noor

**Comment by mourisl** [comment]
I think Chromap will ignore such pairs.

**Comment by NPSDC** [comment]
Thanks
