### ISSUE TITLE
why so slow?

### ISSUE THREAD

**Issue by zhaotao1987** [haowenz/chromap#165]
Hi Haowen,

I used the following command for chromap mapping: 
`        chromap --preset hic -x $index -t $cpu -q $mapQ -r $asm -1 $read1 -2 $read2 --SAM -o $asm.hic.aligned.Q_"$mapQ".sam
`
compared to bwa mem, I found it  not that fast as expected, in actual, much slower even, also it generates over 400 temporary files, and it took hours to merge and combine, could you help and give instruction about how to improve? 
Thanks very much! 
Best, Tao

**Comment by mourisl** [comment]
The sam file is pretty large to merge and generate. How's the speed when outputting in the pairs format?
