### ISSUE TITLE
[BUG] tabix error  [E::hts_idx_push]chromosome blocks not continuous

### ISSUE THREAD

**Issue by lishuangshuang0616** [haowenz/chromap#172]
Will chromap --preset atac sort the generated BED file? I encountered an error when generating a .tbi file using tabix. What could be the reason?

**Comment by mourisl** [comment]
Yes, the output BED file is sorted. Could it be the chromosome name is not sorted lexicographically for tabix? What's the error message from tabix?

**Comment by lishuangshuang0616** [comment]
tabix error [E::hts_idx_push]chromosome blocks not continuous

The order of chromosome names in the genome.fa I provided is out of order. Does that have any impact?
So chromap is sorted according to the chromosome names of the genome, and this caused this error?

**Comment by mourisl** [comment]
Chromap sorts the chromosome following the order in the genome.fa file. I think the tabix assumes the chromosomes are sorted alphabetically. If that's the case, you can put the alphabetically-sorted read ids in a file and put that file for the option "--chr-order". Hope this can resolve the issue.
