### ISSUE TITLE
Own scATAC-seq data test

### ISSUE THREAD

**Issue by sonyumo** [haowenz/chromap#19]
I have my own scATAC-seq data with barcode 20bp. The error is copy below and with 16G core file:

chromap: src/chromap.cc:3892: void chromap::Chromap<MappingRecord>::LoadBarcodeWhitelist() [with MappingRecord = chromap::PairedEndMappingWithBarcode]: Assertion `khash_return_code != -1 && khash_return_code != 0' failed.
/opt/gridengine/default/spool/cngb-compute-e05-8/job_scripts/2110610: line 9: 58354 Aborted                 (core dumped) 

Is there anything in particular that needs attention regarding data formatting(read head, barcode length)? The error maybe caused by the data format.

**Comment by mourisl** [comment]
The current implementation only supports the barcode in 10X format (16bp length). We are working on a new feature for user-defined barcode format. We should be able to have a test version soon (in a few days hopefully).

**Comment by sonyumo** [comment]
Thanks for your reply! Looking forward to the software update！！！！

**Comment by mourisl** [comment]
By the way, if your barcode file is clean (each sequence in the barcode file is just barcode itself), the current Chromap implementation should also be able to handle it.

**Comment by mourisl** [comment]
Sorry, the current implementation only supports at most 16bp barcode. So it still requires the next version...

**Comment by mourisl** [comment]
@sonyumo The version in the branch "custom_read_format"(https://github.com/haowenz/chromap/tree/custom_read_format) supports up to 32bp barcode. Could you please give this branch a try? Once the new features are tested, we will merge it to the main branch.

**Comment by sonyumo** [comment]
OK! I will try these two days!

**Comment by sonyumo** [comment]
I have read the new option, but there is still some questions. My barcode is at the end of read2 with 10bp barcode + 6bp delete + 10bp barcode which means the option "start;end" isn't suits me. Can I use the 10X data mode with 20bp barcode?

**Comment by mourisl** [comment]
Yes, the structure is too complex..you can reformat them into a 20bp barcode.

**Comment by sonyumo** [comment]
I have already convert the format to 10X mode with 20bp barcode. Can I use the code like this: chromap --preset atac -x  -r  -1  -2  -b  --barcode-whitelist ?

**Comment by mourisl** [comment]
Yes.

**Comment by sonyumo** [comment]
Sorry, there still have the error.
Option ‘read-format’ does not exist.
'./chromap-80f75ed_x64-linux/chromap -h' not include the option.

**Comment by mourisl** [comment]
You need to use the "custom_read_format" branch (commit id: b956460).

**Comment by sonyumo** [comment]
Could you please upload the release version of 'custom_read_format'? The 'make' always error.

**Comment by sonyumo** [comment]
I downloaded the 'custom_read_format' source code. But 'make' always have problem. What's wrong with my software?

mkdir -p objs
g++ -std=c++11 -Wall -O3 -fopenmp -march=native -c src/sequence_batch.cc -o objs/sequence_batch.o -lm -lz
g++ -std=c++11 -Wall -O3 -fopenmp -march=native -c src/index.cc -o objs/index.o -lm -lz
g++ -std=c++11 -Wall -O3 -fopenmp -march=native -c src/ksw.cc -o objs/ksw.o -lm -lz
g++ -std=c++11 -Wall -O3 -fopenmp -march=native -c src/chromap.cc -o objs/chromap.o -lm -lz
src/chromap.cc:1106:0: warning: ignoring #pragma omp taskloop [-Wunknown-pragmas]
           #pragma omp taskloop grainsize(grain_size) //num_tasks(num_threads_* 50)
 ^
src/chromap.cc:2015:0: warning: ignoring #pragma omp taskloop [-Wunknown-pragmas]
 #pragma omp taskloop num_tasks(num_threads_* num_threads_)
 ^
src/chromap.cc: In instantiation of ‘void chromap::Chromap<MappingRecord>::MapSingleEndReads() [with MappingRecord = chromap::PAFMapping]’:
src/chromap.cc:4642:47:   required from here
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::PAFMapping>::num_uniquely_mapped_reads_’ is not a variable in clause ‘reduction’
 #pragma omp parallel default(none) shared(reference, index, read_batch, barcode_batch, read_batch_for_loading, barcode_batch_for_loading, std::cerr, num_loaded_reads_for_loading, num_loaded_reads, num_reference_sequences, mappings_on_diff_ref_seqs_for_diff_threads, mappings_on_diff_ref_seqs_for_diff_threads_for_saving, mm_to_candidates_cache, mm_history) num_threads(num_threads_) reduction(+:num_candidates_, num_mappings_, num_mapped_reads_, num_uniquely_mapped_reads_)
         ^
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::PAFMapping>::num_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::PAFMapping>::num_mappings_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::PAFMapping>::num_candidates_’ is not a variable in clause ‘reduction’
src/chromap.cc: In instantiation of ‘void chromap::Chromap<MappingRecord>::MapSingleEndReads() [with MappingRecord = chromap::SAMMapping]’:
src/chromap.cc:4645:47:   required from here
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::SAMMapping>::num_uniquely_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::SAMMapping>::num_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::SAMMapping>::num_mappings_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::SAMMapping>::num_candidates_’ is not a variable in clause ‘reduction’
src/chromap.cc: In instantiation of ‘void chromap::Chromap<MappingRecord>::MapSingleEndReads() [with MappingRecord = chromap::MappingWithBarcode]’:
src/chromap.cc:4649:49:   required from here
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::MappingWithBarcode>::num_uniquely_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::MappingWithBarcode>::num_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::MappingWithBarcode>::num_mappings_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<chromap::MappingWithBarcode>::num_candidates_’ is not a variable in clause ‘reduction’
src/chromap.cc: In instantiation of ‘void chromap::Chromap<MappingRecord>::MapSingleEndReads() [with MappingRecord = chromap::MappingWithoutBarcode]’:
src/chromap.cc:4652:49:   required from here
src/chromap.cc:1981:9: error: ‘chromap::Chromap<>::num_uniquely_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<>::num_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<>::num_mappings_’ is not a variable in clause ‘reduction’
src/chromap.cc:1981:9: error: ‘chromap::Chromap<>::num_candidates_’ is not a variable in clause ‘reduction’
src/chromap.cc: In instantiation of ‘void chromap::Chromap<MappingRecord>::MapPairedEndReads() [with MappingRecord = chromap::PairedPAFMapping]’:
src/chromap.cc:4658:47:   required from here
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::num_corrected_barcode_’ is not a variable in clause ‘reduction’
 #pragma omp parallel default(none) shared(reference, index, read_batch1, read_batch2, barcode_batch, read_batch1_for_loading, read_batch2_for_loading, barcode_batch_for_loading, std::cerr, num_loaded_pairs_for_loading, num_loaded_pairs, num_reference_sequences, mappings_on_diff_ref_seqs_for_diff_threads, mappings_on_diff_ref_seqs_for_diff_threads_for_saving, num_mappings_in_mem, max_num_mappings_in_mem, temp_mapping_file_handles_, mm_to_candidates_cache, mm_history1, mm_history2) num_threads(num_threads_) reduction(+:num_candidates_, num_mappings_, num_mapped_reads_, num_uniquely_mapped_reads_, num_barcode_in_whitelist_, num_corrected_barcode_)
         ^
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::num_barcode_in_whitelist_’ is not a variable in clause ‘reduction’
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::num_uniquely_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::num_mapped_reads_’ is not a variable in clause ‘reduction’
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::num_mappings_’ is not a variable in clause ‘reduction’
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::num_candidates_’ is not a variable in clause ‘reduction’
src/chromap.cc:1032:9: error: ‘chromap::Chromap<chromap::PairedPAFMapping>::temp_mapping_file_handles_’ is not a variable in clause ‘shared’
src/chromap.cc:1296: confused by earlier errors, bailing out
Preprocessed source stored into /tmp/cc8jn4dc.out file, please attach this to your bugreport.
make: *** [objs/chromap.o] Error 1

**Comment by mourisl** [comment]
What is your gcc version?

**Comment by sonyumo** [comment]
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)!!

**Comment by mourisl** [comment]
I think Chromap needs to be compiled with gcc version >= 8.0 . Is it available on your system? Thank you.

**Comment by sonyumo** [comment]
Thanks for your reply!
I use gcc version 9.1.0 and it works! But 'make' still have problem as follows. Could you please send me a release version for test?


objs/chromap.o: In function `chromap::Chromap<chromap::MappingWithoutBarcode>::ConstructIndex()':
chromap.cc:(.text._ZN7chromap7ChromapINS_21MappingWithoutBarcodeEE14ConstructIndexEv[_ZN7chromap7ChromapINS_21MappingWithoutBarcodeEE14ConstructIndexEv]+0x60): undefined reference to `chromap::SequenceBatch::InitializeLoading(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/chromap.o: In function `chromap::Chromap<chromap::PAFMapping>::ComputeBarcodeAbundance(unsigned long)':
chromap.cc:(.text._ZN7chromap7ChromapINS_10PAFMappingEE23ComputeBarcodeAbundanceEm[_ZN7chromap7ChromapINS_10PAFMappingEE23ComputeBarcodeAbundanceEm]+0x96): undefined reference to `chromap::SequenceBatch::InitializeLoading(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/chromap.o: In function `chromap::Chromap<chromap::SAMMapping>::ComputeBarcodeAbundance(unsigned long)':
chromap.cc:(.text._ZN7chromap7ChromapINS_10SAMMappingEE23ComputeBarcodeAbundanceEm[_ZN7chromap7ChromapINS_10SAMMappingEE23ComputeBarcodeAbundanceEm]+0x96): undefined reference to `chromap::SequenceBatch::InitializeLoading(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/chromap.o: In function `chromap::Chromap<chromap::MappingWithBarcode>::ComputeBarcodeAbundance(unsigned long)':
chromap.cc:(.text._ZN7chromap7ChromapINS_18MappingWithBarcodeEE23ComputeBarcodeAbundanceEm[_ZN7chromap7ChromapINS_18MappingWithBarcodeEE23ComputeBarcodeAbundanceEm]+0x96): undefined reference to `chromap::SequenceBatch::InitializeLoading(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/chromap.o: In function `chromap::Chromap<chromap::MappingWithoutBarcode>::ComputeBarcodeAbundance(unsigned long)':
chromap.cc:(.text._ZN7chromap7ChromapINS_21MappingWithoutBarcodeEE23ComputeBarcodeAbundanceEm[_ZN7chromap7ChromapINS_21MappingWithoutBarcodeEE23ComputeBarcodeAbundanceEm]+0x96): undefined reference to `chromap::SequenceBatch::InitializeLoading(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/chromap.o:chromap.cc:(.text._ZN7chromap7ChromapINS_16PairedPAFMappingEE23ComputeBarcodeAbundanceEm[_ZN7chromap7ChromapINS_16PairedPAFMappingEE23ComputeBarcodeAbundanceEm]+0x96): more undefined references to `chromap::SequenceBatch::InitializeLoading(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
make: *** [chromap] Error 1

**Comment by sonyumo** [comment]
Installation success!!! I will try the new option! Thanks a lot!

**Comment by sonyumo** [comment]
Software running successfully! One more question! Is Chromap have the step to merge barcode like bap?

**Comment by mourisl** [comment]
Do you mean one cell can have multiple barcodes? We don't have the feature now. It seems the barcode multiplets are determined after alignment and peak calling, so the barcode merge should be in the post-processing steps.

**Comment by sonyumo** [comment]
Yes, If we want to do the step, we need to generate sam file first!

**Comment by haowenz** [comment]
Close this issue since Chromap v0.1.2 supports customized read format.
