### ISSUE TITLE
scATAC-seq sam problem

### ISSUE THREAD

**Issue by sonyumo** [haowenz/chromap#24]
I output the sam file but failed convert to bam. It said "[E::sam_parse1] CIGAR and query sequence are of different length".
I used custom_read_format version!!!

**Comment by haowenz** [comment]
Can you provide a sample of your reads so that we can have a look? Thanks.

**Comment by sonyumo** [comment]
[tmp.zip](https://github.com/haowenz/chromap/files/7028539/tmp.zip)
Here is part of my sam file! Thanks a lot!

**Comment by sonyumo** [comment]
Hi! I just want to know have you got the sam file I provided! And how can how can I deal with this issue?

**Comment by haowenz** [comment]
Sorry for the delay. Can you also provide the command line you used?

**Comment by sonyumo** [comment]
Thanks for your reply! Here is the command line!
chromap --preset atac -x genome.index -r genome.fa -1 *1.fq.gz -2 *_2.fq.gz --barcode-whitelist whitelist.txt --SAM -o ./temp/aln.sam  --read-format bc:0:19,r1:20:-1 --barcode *_1.fq.gz -t 40 --trim-adapters

**Comment by haowenz** [comment]
Thanks for providing the command line. I generated a fix for this issue in "fix_trim" branch and found it works with my data set locally. You can clone the latest code in "fix_trim" branch and test it. Let me know if it works for you.
