### ISSUE TITLE
SAM file didn't contain sequence information

### ISSUE THREAD

**Issue by AssumeAssume** [haowenz/chromap#27]
The sam file generated by -SAM option didn't contain sequence information.
The command used for alignment:
`chromap --preset chip \
        -x ${chromapindex} \
        -r ${genome} \
        -1 ${outdir}//0-clean_data/paired/${key}_val_1.fq \
        -2 ${outdir}//0-clean_data/paired/${key}_val_2.fq \
        --SAM -t ${thread} -q 1 \
        -o ${outdir}//1-chromap/sam/${key}_q1.sam `

The sam output:
`$ samtools view input_1_q1.sam|head -n 10 `
E00517:731:HG57TCCX2:5:1222:27042:52731	97	chr1	16203	50	150M	*	0	0	*	*	NM:i:0	MD:Z:150
E00517:731:HG57TCCX2:5:1218:1905:44310	97	chr1	16352	45	147M	*	0	0	*	*	NM:i:0	MD:Z:147
E00517:731:HG57TCCX2:5:1218:1905:44310	145	chr1	16247	45	148M	*	0	0	*	*	NM:i:5	MD:Z:20G5G88A14A15A1
E00517:731:HG57TCCX2:5:1222:27042:52731	145	chr1	16283	50	150M	*	0	0	*	*	NM:i:0	MD:Z:150
E00517:731:HG57TCCX2:5:1212:29193:35819	97	chr1	16806	18	149M	*	0	0	*	*	NM:i:0	MD:Z:149
E00517:731:HG57TCCX2:5:1212:29193:35819	145	chr1	16688	18	150M	*	0	0	*	*	NM:i:3	MD:Z:8C4C46T89
E00517:731:HG57TCCX2:5:2108:20172:14002	161	chr1	17089	46	150M	*	0	0	*	*	NM:i:0	MD:Z:150
E00517:731:HG57TCCX2:5:2108:20172:14002	81	chr1	17302	46	150M	*	0	0	*	*	NM:i:0	MD:Z:150
E00517:731:HG57TCCX2:5:1212:3224:52994	161	chr1	19167	49	145M	*	0	0	*	*	NM:i:0	MD:Z:145`

Could the information be included?

**Comment by haowenz** [comment]
Were you using the release? It will be there if you use the latest master branch commit.

**Comment by AssumeAssume** [comment]
Thanks for your prompt reply. I used conda to install the chromap previously. I'll try the latest branch.

**Comment by AssumeAssume** [comment]
> Were you using the release or the latest master branch? It will be there if you use the latest master branch commit.

The latest version sovles the problem, thank you.
