### ISSUE TITLE
Strands in ChIP-seq output

### ISSUE THREAD

**Issue by suragnair** [haowenz/chromap#30]
Hi I used the chip preset to align some paired end reads. The aligned reads look like:

```
chr1	10099	10287	N	42	-
chr1	16177	16524	N	48	+
chr1	17443	17594	N	44	-
chr1	17475	17662	N	40	+
```

What do the strands indicate here? The counts of + and - are also not equal (11517045 - and 9372320 +), so they are unlikely to be fragments cut into reads like in tagAlign format.

The maximum size of each line is 2000, which is the default maximum insert length. So what are the strands signifying?

**Comment by mourisl** [comment]
The strand is the strand of the first read.

**Comment by haowenz** [comment]
> The strand is the strand of the first read in a pair (from the read1 file).

We may want to clarify this in the documentation.

**Comment by suragnair** [comment]
Thanks. So this can be treated as a regular fragment file like in the case of scATAC-seq, correct?

**Comment by haowenz** [comment]
> Thanks. So this can be treated as a regular fragment file like in the case of scATAC-seq, correct?

Yes. The BED output contains fragments (for a read pair). In case you need the mapping start and end positions for each read in the read pair, you can add "--TagAlign" to output the mappings of a read pair separately.
