### ISSUE TITLE
can not install chromap

### ISSUE THREAD

**Issue by BioEpi** [haowenz/chromap#34]
Hello,
    Thanks for developing Chromap. I was trying to install it using this command: `conda install -c bioconda chromap`. However, I got the folllowing errors:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.

Do you know how to solve this issue?
Best,

**Comment by haowenz** [comment]
Hi, please try what is suggested in the manual as follows
```
conda install -c bioconda -c conda-forge chromap
```
Let me know if it works or not.

**Comment by BioEpi** [comment]
thanks  a lot.
I still got the same errors.

**Comment by haowenz** [comment]
Did you copy all the output from conda here? It seems that you have some conflicts. Maybe you can try to create a new environment and then install Chromap with the above command.
