### ISSUE TITLE
Compilation error CentOS 7

### ISSUE THREAD

**Issue by ATpoint** [haowenz/chromap#4]
Hello, I get the following compilation errors when `make` on our CentOS7 HPC, can you help me out here?

Here is the log: https://uni-muenster.sciebo.de/s/hMcvWZgEnIKOo0S

...and here the output from the screen:

https://gist.github.com/ATpoint/a3e0d5eb319895ffb4d894667901afd1

**Comment by tzeitim** [comment]
I was about to report the same issue but @ATpoint was faster on the exact same type of system.

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by lh3** [comment]
I can reproduce the issue with gcc-4.8.5 on CentOS 7. For now, you can use the precompiled binary at [this link](https://github.com/haowenz/chromap/releases/download/v0.1/chromap-80f75ed_x64-linux.tar.bz2) (a tar.bz2 file). This was compiled from the current github HEAD.

**Comment by tzeitim** [comment]
It works! I'll try it and report any issues.
Thanks for the fast response!

**Comment by tzeitim** [comment]
Unfortunately I run into a segmentation fault error. I guess one is to directly compile it in my system. Any suggestions are welcome.

```
./chromap --preset hic -x test.index -r ref.fa -1 r1.fq -2 r2.fq -o out.sam --SAM
Preset parameters for Hi-C are used.
Start to map reads.
Parameters: error threshold: 4, min-num-seeds: 2, max-seed-frequency: 500,1000, max-num-best-mappings: 1, max-insert-size: 1000, MAPQ-threshold: 1, min-read-length: 30, bc-error-threshold: 1, bc-probability-threshold: 0.90
Number of threads: 1
Analyze bulk data.
Won't try to remove adapters on 3'.
Won't remove PCR duplicates after mapping.
Will remove PCR duplicates at bulk level.
Won't allocate multi-mappings after mapping.
Only output unique mappings after mapping.
Only output mappings of which barcodes are in whitelist.
Allow split alignment.
Output mappings in SAM format.
Reference file: ref.fa
Index file: test.index
1th read 1 file: r1.fq
1th read 2 file: r2.fq
Output file: out.sam
Loaded all sequences successfully in 3.98s, number of sequences: 1924, number of bases: 1679214157.
Kmer size: 17, window size: 7.
Lookup table size: 177152077, occurrence table size: 309193718.
Loaded index successfully in 8.12s.
Mapped all reads in 0.58s.
Number of reads: 0.
Number of mapped reads: 0.
Number of uniquely mapped reads: 0.
Number of reads have multi-mappings: 0.
Number of candidates: 0.
Number of mappings: 0.
Number of uni-mappings: 0.
Number of multi-mappings: 0.
Segmentation fault
```

**Comment by ATpoint** [comment]
I think this should go into a separate issue to keep this issue focused on the toplevel problem. Be sure that the command runs on the example data of this repo, then on a small subset of your data, to rule out shortages of disk, memory or CPU.

**Comment by haowenz** [comment]
> Unfortunately I run into a segmentation fault error. I guess one is to directly compile it in my system. Any suggestions are welcome.
> 
> ```
> ./chromap --preset hic -x test.index -r ref.fa -1 r1.fq -2 r2.fq -o out.sam --SAM
> Preset parameters for Hi-C are used.
> Start to map reads.
> Parameters: error threshold: 4, min-num-seeds: 2, max-seed-frequency: 500,1000, max-num-best-mappings: 1, max-insert-size: 1000, MAPQ-threshold: 1, min-read-length: 30, bc-error-threshold: 1, bc-probability-threshold: 0.90
> Number of threads: 1
> Analyze bulk data.
> Won't try to remove adapters on 3'.
> Won't remove PCR duplicates after mapping.
> Will remove PCR duplicates at bulk level.
> Won't allocate multi-mappings after mapping.
> Only output unique mappings after mapping.
> Only output mappings of which barcodes are in whitelist.
> Allow split alignment.
> Output mappings in SAM format.
> Reference file: ref.fa
> Index file: test.index
> 1th read 1 file: r1.fq
> 1th read 2 file: r2.fq
> Output file: out.sam
> Loaded all sequences successfully in 3.98s, number of sequences: 1924, number of bases: 1679214157.
> Kmer size: 17, window size: 7.
> Lookup table size: 177152077, occurrence table size: 309193718.
> Loaded index successfully in 8.12s.
> Mapped all reads in 0.58s.
> Number of reads: 0.
> Number of mapped reads: 0.
> Number of uniquely mapped reads: 0.
> Number of reads have multi-mappings: 0.
> Number of candidates: 0.
> Number of mappings: 0.
> Number of uni-mappings: 0.
> Number of multi-mappings: 0.
> Segmentation fault
> ```

It seems that your read files are empty. There might be problems when handling empty input. I will check this later. Can you try it on the test data we provided? Feel free to start another issue regarding this problem if you want.

**Comment by tzeitim** [comment]
I will open a new issue, thanks @ATpoint for the suggestion and @haowenz for the follow up.

**Comment by dawe** [comment]
I could not build with gcc 4.8.5 due to missing omp pragma taskloop (possibly old version of the system compiler). Precompiled binaries didn't work as well due to missing appropriate libraries (I can't install them system-wide), `GLIBCXX_3.4.20` and `GLIBCXX_3.4.21`.
I had some luck building with a recent compiler (conda install -c conda-forge compilers) and modifying the `Makefile`, in particular these three lines:

```
cxx=x86_64-conda-linux-gnu-g++
cxxflags=-std=c++11 -Wall -O3 -fopenmp -march=native -I$(CONDA_PREFIX)/include -fPIE
ldflags=-L$(CONDA_PREFIX)/lib -lm -lz
```

**Comment by lh3** [comment]
I have just replaced the precompiled binaries on the release page. You can try that. It should work on CentOS 7.

**Comment by mourisl** [comment]
Chromap is also available on conda now: https://anaconda.org/bioconda/chromap or https://anaconda.org/liulab-dfci/chromap. We will update README soon.

**Comment by ATpoint** [comment]
The binaries work fine on CentOS-7 with the provided test data.

The conda build for mac does not work though.

```
$ mamba install -c liulab-dfci chromap

Looking for: ['chromap']

liulab-dfci/osx-64       [====================] (00m:00s) Done
liulab-dfci/noarch       [====================] (00m:00s) Done
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/osx-64         [====================] (00m:08s) Done
pkgs/main/noarch         [====================] (00m:01s) Done
bioconda/osx-64          [====================] (00m:14s) Done
conda-forge/noarch       [====================] (00m:15s) Done
bioconda/noarch          [====================] (00m:15s) Done
conda-forge/osx-64       [====================] (00m:25s) Done
Encountered problems while solving:
  - nothing provides libgcc-ng >=9.3.0 needed by chromap-0.1-h3fd9d12_0
```

**Comment by dawe** [comment]
> I have just replaced the precompiled binaries on the release page. You can try that. It should work on CentOS 7.

It works, thank you!

**Comment by liz-is** [comment]
Any chance of getting precompiled binaries for an up-to-date release version of chromap? :)

I'm keen to try it but currently struggling to install a recent enough version of gcc on our system (CentOS7, hence why I'm posting in this thread). I would prefer not to use conda as I've had bad experiences with it in the past.

**Comment by lh3** [comment]
@liz-is I have uploaded a binary tarball for v0.1.3. Could you have a try?

**Comment by lh3** [comment]
Just to clarify the cause and the solution. CentOS 7 has gcc-4.8.5 by default. It supports C++11 but it lacks OpenMP v4 features required by chromap. We can compile chromap on a different Linux distribution but the precompiled binary may not work on CentOS 7 due to incompatibility of glibc (I just hate this).

The solution is to compile on CentOS 7 with a more recent gcc that supports OpenMP v4 features. The binary on the release page is compiled by gcc-6.4.0 on CentOS 6. I compiled this gcc-6.4.0 myself from the source code on another CentOS 6.

**Comment by liz-is** [comment]
Thank you very much! It works for me, I'm looking forward to trying it out on more datasets.

**Comment by haowenz** [comment]
Starting from v0.2.0, we will attach a precompiled binary for each tagged release.
