### ISSUE TITLE
Chromap for processing the complex barcodes

### ISSUE THREAD

**Issue by lin-zhongbao** [haowenz/chromap#42]
Hi!

Apologies if I have missed this somewhere, and I am trying to process some scATAC-Seq data with chromap, there were more than one barcode and UMI molecular in the data, which there were two link sequence in the barcode reads and barcodes were not continuous. 

chromap can process this data?

if so, how about the barcode mode is BC1+Adaptor1+BC2+Adaptor2+BC3+Adaptor3+BC4+UMI+PolyT?
BC1=8bp,BC2=8bp,BC3=8bp,BC4=8bp,UMI=12bp,Adaptor1=30bp,Adaptor2=25bp,Adaptor3=20bp

Thanks
Tao

**Comment by mourisl** [comment]
Hi Tao, Chromap only supports continuous barcode sequences, so you need to generate a new barcode file by concatenating those barcode segments.

**Comment by AlicePsyche** [comment]
Hi @lin-zhongbao 

I am just wondering if you have found a more elegant solution now. I am working on a similar dataset as you, scATAC-seq with combinatory indexing. Is there any tool that can extract the CB just like `kalliso`? Seems to be a common feature in scRNA-seq mapping software but not in the ATAC field.  Thanks in advance, any suggestions are appreciated. 

Best,
Alice

**Comment by mourisl** [comment]
We have updated the --read-format option to accommodate the complex barcode by using multiple bc fields. UMI is not used in Chromap, but for the barcode, you can use the option: --read-format bc:0:7,bc:38:45,bc:66:73,bc:94:101

**Comment by AlicePsyche** [comment]
Hi, I just tried it on my new datasets. Combined with the whitelist, it worked extremely well!!!! Great thanks!! (Also, kind of shocked to see how fast it is now.....nearly 1min for 10M reads.....

**Comment by badoi** [comment]
@AlicePsyche how are you using the whitelist using the split barcode? is your barcode whitelist for each split segment or for the combined sequence?
