### ISSUE TITLE
Duplicates in preset Hi-C mode

### ISSUE THREAD

**Issue by jimwry** [haowenz/chromap#44]
Hi!

I have a quick question regarding PCR duplicates in Hi-C preset, does PCR duplicates get removed already in the output pairs (4DN format)?  Could not find this information in the manual page. 

Thank you so much!

Jim

**Comment by mourisl** [comment]
Chromap does not remove PCR duplicates in Hi-C through the preset option. You can find the information at the bottom of the manual page here: https://zhanghaowen.com/chromap/chromap.html .

If you want to remove the duplicates, you can add the option "--remove-pcr-duplicates".

**Comment by jimwry** [comment]
> Chromap does not remove PCR duplicates in Hi-C through the preset option. You can find the information at the bottom of the manual page here: https://zhanghaowen.com/chromap/chromap.html .
> 
> If you want to remove the duplicates, you can add the option "--remove-pcr-duplicates".

Great, thank you so much!

**Comment by mourisl** [comment]
I just want to mention one of the main reasons that we did not add the PCR deduplication as the default behavior. The deduplication is based on alignment coordinates, and we did not keep track of the internal alignment breakpoint (ligation site) in Hi-C data. So if two read pairs have the same endpoints, but have different ligation sites, one of them will still be removed in the deduplication step.

**Comment by jimwry** [comment]
> I just want to mention one of the main reasons that we did not add the PCR deduplication as the default behavior. The deduplication is based on alignment coordinates, and we did not keep track of the internal alignment breakpoint (ligation site) in Hi-C data. So if two read pairs have the same endpoints, but have different ligation sites, one of them will still be removed in the deduplication step.

Thank you for your detailed explanation. That make senses. I just want to clarify that, only read pairs, of which both end reads are duplicated, will be considered as duplicates in chromap? Thanks!
