### ISSUE TITLE
Documentation for dedeuplication algorithms used

### ISSUE THREAD

**Issue by chris-cheshire** [haowenz/chromap#61]
Thank you for this excellent tool!

I cannot find any reference to how you remove PCR duplicates. Can you confirm it is similar to the 10x "new" method? If you do not have a barcode whitelist - how do you remove duplicates at the cell level?

https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/algorithms/overview

I think the documentation could be extended to include more complete descriptions of your algorithms in general.

**Comment by haowenz** [comment]
If you use the atac preset parameters,  `--remove-pcr-duplicates-at-cell-level` will be set. Then the duplicates will be removed at cell level as the 10x "new" method. If you don't have a barcode whitelist, Chromap can still use the uncorrected barcodes to remove duplicates at cell level. Thanks for you suggestions. We will improve the document on this.

**Comment by haowenz** [comment]
> Thanks for your quick response - can you confirm duplicates are identified using START/END/BARCODE? 

If you deduplicate at cell level, then yes. For paired-end reads, the fragment (that contains the two reads) as a whole is considered. So the start and the end of two fragments (and their barcodes) have to be the same to be considered as duplicates.

> How is the primary duplicate chosen? Is this based on the quality score? 

Mapping with highest MAPQ is chosen as primary for cell-level deduplication. For bulk-level deduplication (same as 10x "old" method), we find the most frequent barcode for the dups, and break ties by the barcode abundance when necessary.

> Can you also comment on how your read trimming is performed? Is this similar to cutadapt?

For now, Chromap only does one type of adapter trimming. When two reads are overlapped and the fragments are actually shorter than read length. We found this very common in ATAC-seq. For more details, you can look at the Supplementary Figure 5 in the paper, which is an example and makes things easier to understand.

**Comment by chris-cheshire** [comment]
Thanks so much for all your comments, its really nice to use a well supported tool.
