### ISSUE TITLE
ATAC Assertion `barcode_length

### ISSUE THREAD

**Issue by sonyumo** [haowenz/chromap#80]
Hi~
    I got the following error:  
   "chromap: src/chromap.cc:4493: void chromap::Chromap<MappingRecord>::LoadBarcodeWhitelist() [with MappingRecord = chromap::PairedEndMappingWithBarcode]: Assertion `barcode_length == barcode_length_' failed."

--read-format bc:0:19,r1:20:-1
whitelist.txt :CTATGTATAACTATGTATAA 20bp.

I don't know why this error occurs. 

Thank you!

**Comment by haowenz** [comment]
Which version were you using? It seems that your whitelist has various-length barcodes, which caused the issue.

**Comment by sonyumo** [comment]
chromap-0.1.6!

**Comment by rpolicastro** [comment]
In case anyone encounters this error and their barcode whitelist file is zipped, unzipping it resolved the issue for me.
