### ISSUE TITLE
Prebuilt binary Chromap v0.2.2

### ISSUE THREAD

**Issue by NMaziak** [haowenz/chromap#94]
Hello, 

I was wondering if you could release a pre-built binary again for the newest version? 

Many thanks for all the help, 
Noura

**Comment by haowenz** [comment]
We already released a binary for v0.2.2 (r388). By the newest version, do you mean including more changes after v0.2.2 (r388)?

**Comment by NMaziak** [comment]
Hello, yes very sorry! I somehow managed to miss the fact that it was already there. Would v0.2.2 include a solution to https://github.com/haowenz/chromap/issues/70 this issue by any chance?

**Comment by haowenz** [comment]
Yes. It was resolved long time ago.
